import { Info, HelpCircle, Layers, Activity, TrendingUp, CheckCircle } from 'lucide-react';

export default function EducationalGuide() {
  return (
    <div className="bg-white rounded-2xl border border-slate-100 p-6 md:p-8 space-y-8" id="educational_guide">
      <div className="flex items-center gap-3 border-b border-slate-100 pb-4">
        <HelpCircle className="w-6 h-6 text-indigo-600" id="edu_icon_help" />
        <div>
          <h2 className="text-xl font-sans font-medium text-slate-900 leading-tight">Educational Guide & Core Concepts</h2>
          <p className="text-sm font-sans text-slate-500">Learn how these machine learning algorithms split profiles and vote</p>
        </div>
      </div>

      {/* Grid of decision tree vs random forest */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6" id="edu_concept_grid">
        {/* Decision Tree Card */}
        <div className="bg-slate-50 rounded-xl p-5 border border-slate-100 space-y-4" id="edu_dt_card">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-indigo-50 flex items-center justify-center border border-indigo-100">
              <Activity className="w-4 h-4 text-indigo-600" id="edu_dt_icon" />
            </div>
            <h3 className="font-sans font-medium text-slate-800">Concept of Prediction: Decision Tree</h3>
          </div>
          
          <p className="text-sm font-sans text-slate-600 leading-relaxed">
            A <strong>Decision Tree</strong> segments patients step-by-step using split parameters. At each junction (node), the algorithm chooses the clinical feature that best groups patient observations into highly uniform disease classes.
          </p>

          <div className="bg-white rounded-lg p-4 border border-slate-200/60 font-mono text-xs text-slate-700 space-y-2">
            <div className="text-indigo-600 font-semibold mb-1">// Traversal Logic Example:</div>
            <div>{"Age > 60?"}</div>
            <div className="pl-4">├── Yes: {"Unhealthy Cholesterol (Cholesterol > 240)?"}</div>
            <div className="pl-8 text-red-500">├── Yes ➔ Coronary Artery Disease</div>
            <div className="pl-8 text-blue-500">└── No ➔ Heart Failure</div>
            <div>{"└── No: Abnormal ECG?"}</div>
            <div className="pl-4 text-orange-500">├── Yes ➔ Heart Arrhythmias</div>
            <div className="pl-4 text-emerald-500">└── No ➔ Healthy / Low Risk</div>
          </div>

          <div className="space-y-2">
            <h4 className="text-xs font-sans font-semibold text-slate-700 uppercase tracking-widest flex items-center gap-1">
              <TrendingUp className="w-3.5 h-3.5 text-indigo-500" />
              Gini Impurity & Information Gain
            </h4>
            <p className="text-xs font-sans text-slate-500 leading-relaxed">
              Splits are generated by evaluating the <strong>Gini Impurity</strong>. Gini measures how diverse or mixed a node is. An impurity of 0 occurs if a node contains patients of one single disease class. The algorithm chooses split thresholds representing the highest reduction in impurity (Information Gain).
            </p>
          </div>
        </div>

        {/* Random Forest Card */}
        <div className="bg-slate-50 rounded-xl p-5 border border-slate-100 space-y-4" id="edu_rf_card">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-emerald-50 flex items-center justify-center border border-emerald-100">
              <Layers className="w-4 h-4 text-emerald-600" id="edu_rf_icon" />
            </div>
            <h3 className="font-sans font-medium text-slate-800">Concept of Prediction: Random Forest</h3>
          </div>

          <p className="text-sm font-sans text-slate-600 leading-relaxed">
            To prevent overfitting, a <strong>Random Forest</strong> combines multiple independent decision trees that train simultaneously and then aggregates their classifications to determine the patient state.
          </p>

          <div className="bg-white rounded-lg p-4 border border-slate-200/60 font-mono text-xs text-slate-700 space-y-2">
            <div className="text-emerald-600 font-semibold mb-1">// Aggregate Forest Votes Example:</div>
            <div className="grid grid-cols-2 gap-1 py-1 border-b border-dashed border-slate-100">
              <div>🌳 Tree 1 Predicts:</div>
              <div className="text-red-500 font-medium">CAD</div>
              <div>🌳 Tree 2 Predicts:</div>
              <div className="text-red-500 font-medium">CAD</div>
              <div>🌳 Tree 3 Predicts:</div>
              <div className="text-blue-500 font-medium">Heart Failure</div>
              <div>🌳 Tree 4 Predicts:</div>
              <div className="text-red-500 font-medium">CAD</div>
            </div>
            <div className="flex justify-between items-center bg-emerald-50/50 p-1.5 rounded mt-2">
              <span className="font-sans font-semibold text-slate-800">Final Forest Outcast:</span>
              <span className="text-red-600 font-bold">CAD (75% Votes)</span>
            </div>
          </div>

          <div className="space-y-3">
            <div className="grid grid-cols-2 gap-3">
              <div className="bg-white p-2.5 rounded border border-slate-100">
                <span className="block text-xs font-semibold text-slate-700">Bootstrapping (Bagging)</span>
                <span className="block text-[11px] text-slate-500 mt-1 leading-normal">
                  Each tree trains on a randomly sampled dataset drawn with replacement.
                </span>
              </div>
              <div className="bg-white p-2.5 rounded border border-slate-100">
                <span className="block text-xs font-semibold text-slate-700">Feature Bagging</span>
                <span className="block text-[11px] text-slate-500 mt-1 leading-normal">
                  At each split, only a subset of clinical fields is examined, creating diverse trees.
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Comparison Metrics */}
      <div className="border-t border-slate-100 pt-6 space-y-4" id="edu_tradeoffs">
        <h3 className="font-sans font-medium text-slate-800 flex items-center gap-2">
          <Info className="w-4 h-4 text-indigo-500" />
          General Trade-offs & Clinical Advantages
        </h3>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs font-sans">
          <div className="p-3 bg-indigo-50/40 rounded-lg border border-indigo-100/40">
            <span className="font-semibold text-indigo-900 block mb-1">Explainability Check</span>
            <span className="text-indigo-950/75 leading-relaxed">
              <strong>Single Decision Trees</strong> are fully visual and intuitive. Clinicians can trace patient paths easily. Random Forests are an ensemble of many trees making them harder to trace, often called &quot;black box&quot; models.
            </span>
          </div>

          <div className="p-3 bg-emerald-50/40 rounded-lg border border-emerald-100/40">
            <span className="font-semibold text-emerald-900 block mb-1">Stability & Overfitting</span>
            <span className="text-emerald-950/75 leading-relaxed">
              Single Decision Trees are highly sensitive to sample edits or noise, leading to overfitting. <strong>Random Forests</strong> handle data variations elegantly by averaging errors across hundreds of bootstrap networks.
            </span>
          </div>

          <div className="p-3 bg-violet-50/40 rounded-lg border border-violet-100/40">
            <span className="font-semibold text-violet-900 block mb-1">Clinical Deployment</span>
            <span className="text-violet-950/75 leading-relaxed">
              Historically, Random Forests provide better generalization metrics for heart disease risk analysis, while single Decision Trees are used as fast diagnostic trees for emergency room triage.
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}
